site_name: EKS Best Practices Guides
repo_name: 'aws/aws-eks-best-practices'
repo_url: 'https://github.com/aws/aws-eks-best-practices'
docs_dir: 'content'
theme: 
  name: material
  icon: 
    repo: fontawesome/brands/github
  features: 
    - tabs
nav:
  - Guides: 
    - Introduction: 'index.md'
  - Security:
    - Home: 'security/docs/index.md'
    - Identity and Access Management: 'security/docs/iam.md'
    - Pod Security: 'security/docs/pods.md'
    - Multi-tenancy: 'security/docs/multitenancy.md'
    - Detective Controls: 'security/docs/detective.md'
    - Network Security: 'security/docs/network.md'
    - Data Encryption and Secrets Management: 'security/docs/data.md'
    - Runtime Security: 'security/docs/runtime.md'
    - Infrastructure Security: 'security/docs/hosts.md'
    - Regulatory Compliance: 'security/docs/compliance.md'
    - Incident Response and Forensics: 'security/docs/incidents.md'
    - Image Security: 'security/docs/image.md'
  - Cluster Autoscaling: 
    - Karpenter: 'karpenter/index.md'
    - Cluster-Autoscaler: 'cluster-autoscaling/index.md'
  - Reliability:
    - Home: 'reliability/docs/index.md'
    - Applications: 'reliability/docs/application.md'
    - Control Plane: 'reliability/docs/controlplane.md'
    - Data Plane: 'reliability/docs/dataplane.md'
    - Network: 'reliability/docs/networkmanagement.md'
  - Windows Containers: 
    - AMI Management: 'windows/docs/ami.md'
    - gMSA for Windows Containers: 'windows/docs/gmsa.md'
    - Windows Server Hardening: 'windows/docs/hardening.md'
    - Running Mixed Workloads: 'windows/docs/heterogeneous.md'
    - Scanning Windows Images: 'windows/docs/images.md'
    - Windows Versions and Licensing: 'windows/docs/licensing.md'
    - Logging: 'windows/docs/logging.md'
    - Monitoring Windows Containers: 'windows/docs/monitoring.md'
    - Windows Networking: 'windows/docs/networking.md'
    - Memory and Systems Management: 'windows/docs/oom.md'
    - Infrastructure Management: 'windows/docs/patching.md'
    - Scheduling: 'windows/docs/scheduling.md'
    - Pod Security for Windows Containers: 'windows/docs/security.md'
    - Storage Options: 'windows/docs/storage.md'
  - Networking:
    - Home: 'networking/index/index.md'
    - VPC and Subnet Considerations: 'networking/subnets/index.md'
    - Amazon VPC CNI: 'networking/vpc-cni/index.md'
    - Prefix Mode: 'networking/prefix-mode/index.md'
    - Running IPv6 Clusters: 'networking/ipv6/index.md'
    - Security Groups per Pod: 'networking/sgpp/index.md'
    - Custom Networking: 'networking/custom-networking/index.md'
    - Load Balancing: 'networking/loadbalancing/loadbalancing.md'
    - Monitoring for DNS Throttling Issues: 'networking/CoreDNS/index.md'
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true

plugins: 
    - search
    - i18n:
        default_language: en
        languages:
          en:
            name: English
            build: true
          kr:
            name: '한국어'
            build: true
            site_name: 'EKS 모범 사례 가이드'
        nav_translations:
          kr:
            Guides: '가이드'
            Introduction: '소개'
            Security: '보안'
            Identity and Access Management: '인증 및 접근 관리'
            Pod Security: 'Pod 보안'
            Multi-tenancy: '멀티 테넌시'
            Detective Controls: '탐지 관리'
            Network Security: '네트워크 보안'
            Data Encryption and Secrets Management: '데이터 암호화 및 시크릿 관리'
            Runtime Security: '런타임 보안'
            Infrastructure Security: '인프라 보안'
            Regulatory Compliance: '컴플라이언스'
            Incident Response and Forensics: '사고 대응 및 포렌식'
            Image Security: '이미지 보안'
            Cluster Autoscaling: '클러스터 오토스케일링'
            Karpenter: 'Karpenter'
            Cluster-Autoscaler: 'Cluster Autoscaler'
            Reliability: '신뢰성'
            Home: '홈'
            Applications: '애플리케이션'
            Control Plane: '컨트롤 플레인'
            Data Plane: '데이터 플레인'
            Network: '네트워크'
            Windows Containers: '윈도우 컨테이너'
            AMI Management: 'AMI 관리'
            gMSA for Windows Containers: 'gMSA 윈도우 컨테이너'
            Windows Server Hardening: '윈도우 서버 하드닝'
            Running Mixed Workloads: '혼합 워크로드 실행'
            Scanning Windows Images: '윈도우 이미지 스캔'
            Windows Versions and Licensing: '윈도우 버전 및 라이선스'
            Logging: '로깅'
            Monitoring Windows Containers: '윈도우 컨테이너 모니터링'
            Windows Networking: '윈도우 네트워크'
            Memory and Systems Management: '메모리 및 시스템 관리'
            Infrastructure Management: '인프라 관리'
            Scheduling: '스케줄링'
            Pod Security for Windows Containers: '윈도우 컨테이너 Pod 보안'
            Storage Options: '스토리지 옵션'
            Networking: '네트워크'
            VPC and Subnet Considerations: 'VPC 및 서브넷 고려사항'
            Amazon VPC CNI: 'Amazon VPC CNI'
            Prefix Mode: 'Prefix 모드'
            Running IPv6 Clusters: 'IPv6 클러스터 실행'
            Security Groups per Pod: 'Pod 보안 그룹 할당'
            Custom Networking: 'Custom Networking'
            Load Balancing: '로드 밸런싱'
            Monitoring for DNS Throttling Issues: 'DNS 쓰로틀링 모니터링'

      
extra:
  analytics:
    provider: google
    property: G-VQGL8B2FH8
  